form_settings:
  aggregator_feed:
    default_value: false
    disable: false
    hidden: false
  aggregator_item:
    default_value: false
    disable: false
    hidden: false
  block_content:
    default_value: false
    disable: false
    hidden: false
  comment:
    default_value: false
    disable: false
    hidden: false
  contact_message:
    default_value: false
    disable: false
    hidden: false
  content_moderation_state:
    default_value: false
    disable: false
    hidden: false
  entity_subqueue:
    default_value: false
    disable: false
    hidden: false
  file:
    default_value: false
    disable: false
    hidden: false
  flagging:
    default_value: false
    disable: false
    hidden: false
  media:
    default_value: false
    disable: false
    hidden: false
  node:
    default_value: false
    disable: false
    hidden: false
  profile:
    default_value: false
    disable: false
    hidden: false
  shortcut:
    default_value: false
    disable: false
    hidden: false
  taxonomy_term:
    default_value: false
    disable: false
    hidden: false
  user:
    default_value: false
    disable: false
    hidden: false
  vote:
    default_value: false
    disable: false
    hidden: false
  vote_result:
    default_value: false
    disable: false
    hidden: false
  webform_submission:
    default_value: false
    disable: false
    hidden: false
  font:
    default_value: false
    disable: false
    hidden: false
  menu_link_content:
    default_value: false
    disable: false
    hidden: false
