unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: true
log: false
element_name: url
time_limit: 0
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_feedback_form: false
  contact_message_personal_form: false
  node_article_form: false
  node_condition_form: false
  node_connect_tool_form: false
  node_diy_tool_form: false
  node_geolocation_default_article_form: false
  node_homepage_slide_form: false
  node_page_form: false
  node_referral_to_treatment_profile_form: false
  node_treatment_info_form: false
  node_webform_form: false
  node_webform_demo_event_form: false
  comment_comment_form: false
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
