theme: s2s
defaults:
  sender: webform_php_mail
  formatter: webform_php_mail
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  swiftmailer: {  }
  webform:
    none: {  }
