schemas:
  bootstrap: 8000
  s2s: 8000
logo:
  path: 'public://logo.png'
  url: ''
  use_default: false
region_wells:
  navigation: ''
  navigation_collapsible: ''
  top_navigation: ''
  header: ''
  highlighted: ''
  help: ''
  slider: ''
  content: ''
  content_full_width_total: ''
  content_full_width: ''
  sidebar_first: ''
  sidebar_second: ''
  superfooter_1: ''
  superfooter_2: ''
  superfooter_3: ''
  superfooter_4: ''
  superfooter_5: ''
  superfooter_6: ''
  superfooter_7: ''
  footer: ''
table_responsive: '-1'
table: ''
favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon.ico'
  url: 'http://default/sites/default/files/favicon.ico'
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
