content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  administrator: 3
  mha_admin: 4
  mha_affiliate: 5
  mha_affiliate_no_form: 6
_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
content_access_node_type:
  page: 'a:1:{s:8:"per_node";i:1;}'
  forum: 'a:2:{s:8:"view_own";a:1:{i:0;s:13:"authenticated";}s:4:"view";a:1:{i:0;s:13:"authenticated";}}'
