module:
  address: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  ban: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  block_exclude_pages: 0
  breakpoint: 0
  bwm_mods: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  conditional_fields: 0
  config: 0
  content_access: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_advanced_link: 0
  entity_browser: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_autocomplete: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  geofield_map: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  imce: 0
  kint: 0
  link: 0
  linkit: 0
  mailsystem: 0
  menu_breadcrumb: 0
  menu_token: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_views: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_multilingual: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  mimemail: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  rest: 0
  rules: 0
  salesforce: 0
  salesforce_logger: 0
  salesforce_mapping: 0
  salesforce_pull: 0
  salesforce_push: 0
  search: 0
  serialization: 0
  shortcut: 0
  simplenews: 0
  superfish: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  typed_data: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_ui: 0
  webform: 0
  webform_devel: 0
  webform_image_select: 0
  webform_migrate: 0
  webform_node: 0
  webform_scheduled_email: 0
  webform_submission_log: 0
  webform_ui: 0
  webform_views: 0
  contribute: 1
  extlink: 1
  fontyourface: 1
  forum: 1
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  google_fonts_api: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  enterpriseplus: 0
  adminimal_theme: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: standard
