definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    weight: -74
    menu_name: main
    parent: ''
    enabled: false
    expanded: false
  user__page:
    menu_name: account
    parent: ''
    weight: -99
    expanded: false
    enabled: true
  user__logout:
    weight: -65
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
